version: '3'

services:
  db:
    image: postgres
    ports:
      - "${DB__PORT}:5432"
    environment:
      PGUSER: ${DB__USERNAME}
      PGPASSWORD: ${DB__PASSWORD}
      PGDATABASE: ${DB__NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PGUSER} -d $${PGDATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  audiofiles_app:
    build: .
    ports:
      - 8000:8000
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    environment:
      - DB__HOSTNAME=db
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
    driver: local